public with sharing class AccountFeatureHandler
//	implements ITrigger
{	
	/*//Boolean newData = false;
	public AccountFeatureHandler()
	{
		//newData = false;
	}
	public void bulkBefore()
	{
	}
	
	public void bulkAfter()
	{
	}
		
	public void beforeInsert(SObject so)
	{
		//AccountFeatureService.enforceValues((Account_Feature__c)so);
		//AccountFeatureService.calcExpirationDate((Account_Feature__c)so);
	}
	
	public void beforeUpdate(SObject oldSo, SObject so)
	{
		//AccountFeatureService.enforceValues((Account_Feature__c)so);
		//AccountFeatureService.calcExpirationDate((Account_Feature__c)so);
	}
	public void beforeDelete(SObject so)
	{	
	}
	
	public void afterInsert(SObject so)
	{
		//newData = true;
	}
	
	public void afterUpdate(SObject oldSo, SObject so)
	{
	}
	
	public void afterDelete(SObject so)
	{
	}
	public void andFinally()
	{
		//try{
		//	if(newData)admin_utilities.syncFeaturesAtFuture();
		//}
		//catch(Exception e){}
	}*/
}