/**
 * Controller for the Portal IoT landing page components
 * 
 * @Version 1.0.0
 * @description LandingPageController
 * Version History
 * -----------------------------------------------------------------------------------------------
 * 1.1.0        Created
 * 2021-11-16   deyelchaninov@deloitte.de
 * 
 */
public with sharing class LandingPageController {
    /**
     * @description Frontend method to fetch all Topics, to be shown on landing page. 
     * 
     * @return      String Array of all Topics
     * 
     * @author      deyelchaninov@deloitte.de
     * @date        2021-11-16
     */
    

    /**
     * @description Frontend method to fetch all Topics, to be shown on landing page. 
     * 
     * @return      String Array of all Topics
     * 
     * @author      deyelchaninov@deloitte.de
     * @date        2021-11-16
     */
    
     /**
     * @description Frontend method to fetch all Topics, to be shown on landing page. 
     * 
     * @return      String Array of all Topics
     * 
     * @author      deyelchaninov@deloitte.de
     * @date        2021-11-16
     */
    

    /**
     * @description merhod to fetch solutions for specified segments
     * 
     * @param segments list of segment ids
     * 
     * @return      PortalSearchResult object containing solutions
     * 
     * @author      deyelchaninov@deloitte.de
     * @date        2021-11-16
     */
    
    /**
     * @description merhod to fetch articles for specified segments
     * 
     * @param segments list of segment ids
     * 
     * @return      PortalSearchResult object containing articles
     * 
     * @author      deyelchaninov@deloitte.de
     * @date        2021-11-16
     */
    

    /**
     * @description merhod to fetch articles for specified segments
     * 
     * @param portalSearch
     * 
     * @return      PortalSearchResult object containing articles
     * 
     * @author      deyelchaninov@deloitte.de
     * @date        2021-11-16
     */
    

    /**
     * @description merhod to fetch all segments info
     * 
     * @return      list of CategoryWrapper of all segments
     * 
     * @author      deyelchaninov@deloitte.de
     * @date        2022-01-18
     */
   
		//Don't delete the if 
            //if(!result.isEmpty()){
                //result[0].active = true;
            //}
          

    /**
     * @description method to fetch all topics info for Slider
     * 
     * @param       languageFilter Filter String for language
     * @return      List of CategoryWrapper with the topic data for slider
     * 
     * @author      pkriegbaum@deloitte.de
     * @date        2022-06-14
     */
    

    /**
     * @description method to fetch custom information stored on user object
     * 
     * @return      UserWrap - user information wrapped for easier handling on frontend
     * 
     * @author      deyelchaninov@deloitte.de
     * @date        2022-03-09
     */
   

    /**
     * @description method to fetch information on last searched products
     * 
     * @return      PortalSearchResult - information wrapped in psr object
     * 
     * @author      deyelchaninov@deloitte.de
     * @date        2022-03-10
     */
   
     /**
     * @description method to fetch information on mentioned product Ids 
     * 
     * @param      idListString semi-colon separated string of product ids
     * 
     * @return      PortalSearchResult - information wrapped in psr object
     * 
     * @author      svivekkalsekar@deloitte.com
     * @date        2022-06-07
     */
  
    
    
    /**
     * @description method to fetch information on last viewed articles
     * 
     * @return      List<ArtWrap> - information wrapped in psr object
     * 
     * @author      deyelchaninov@deloitte.de
     * @date        2022-03-106
     */
   
     /**
     * @description method to fetch information on last viewed discussions
     * 
     * @return      List<DiscWrap> - information wrapped in psr object
     * 
     * @author      svivekkalsekar@deloitte.com
     * @date        2022-04-14
     */
    
    /**
     * @description method to fetch information on last viewed discussions
     * 
     * @return      List<DiscWrap> - information wrapped in psr object
     * 
     * @author      svivekkalsekar@deloitte.com
     * @date        2022-04-14
     */
  

    //Added for SCA fix for TKT-000804 on 14th Sept, 2022 by svivekkalsekar@deloitte.com (start)
           /**
         * @description SobjectWrapper
 		 */
   
    //Added for SCA fix for TKT-000804 on 14th Sept, 2022 by svivekkalsekar@deloitte.com (end)
                            /**
         * @description DiscTopicWrap
 		*/
       /**
         * @description DiscTopicWrap
         * @param top 
 		 */
          /**
         * @description DiscWrap
 		*/
                        /**
         * @description DiscWrap
         * @param feedItemObject 
 		*/
      

            /**
         * @description ArtWrap
 		*/
                /**
         * @description ArtWrap
         * @param art 
 		*/
       
	/**
 	* @description UserWrap
 	*/
        /**
         * @description UserWrap
         * @param us 
 		*/
        /*
		* @description 
		*/ 
        /*
		* @description 
		*/ 
        /*
		* @description 
		*/ 
        /*
		* @description 
		*/ 
    

    // Class for wrapping category data for usage in the Landing Page Welcome carousel
    /**
 	* @description CategoryWrapper
 	*/
        /*
		* @description id field
		*/ 
		/*
		* @description 
		*/ 
		/*
		* @description 
		*/ 
		/*
		* @description 
		*/ 
		/*
		* @description 
		*/ 
		/*
		* @description 
		*/ 
		/*
		* @description 
		*/ 
		/*
		* @description 
		*/ 
		/*
		* @description 
		*/ 
		/*
		* @description 
		*/ 
		/* 
		 * @description active 
		*/ 
       
}