public class TemperatureConverter {
    // Takes a Fahrenheit temperature and returns the Celsius equivalent.
    public static Decimal fhToCels123(Decimal fh) {
        Decimal cels = (fh - 32) * 5/9;
        System.debug('Copado Rocks - updated!!!');
        system.debug('More Conflict');
        System.debug('Additional Line - updated - v2 version!!');
        return cels.setScale(2);
        
        //This is US-2 Commit-3
        
        //This is US-1 commit-1
        
        //This is US-2 Commit-4
        
        //This is US-2 Commit-2
    }

}