.ltuiLearningObjectRichTextCmp .rich-text-section-title {
	font-weight: bold;
	font-size: 20px; 
}

.ltuiLearningObjectRichTextCmp ul li a {
	 font-size: larger; 
}

.ltuiLearningObjectRichTextCmp ul li a:hover, .ltuiLearningObjectRichTextCmp ul li a:focus {
    font-weight: bold;
    padding-left: 10px;
    margin-left: -15px;
}

div.ltuiLeaderboardCmp .user-name {
	white-space: normal;
}