{
   "total":1,
   "nextOffset":1,
   "lastTxnId":null,
   "data":[
      {
         "company_id":"a"
         , "account_id":null
         , "product_id":"product"
         , "product_name":"product"
         , "buying_stage":"Stage"
         , "intent_score":"10"
         , "profile_fit":"Strong"
         , "profile_score":0
         , "txn_id":1
         , "updated":"2017-01-01 02:51:01"
      }
   ]
}