{
   "total":1,
   "nextOffset":1,
   "lastTxnId":null,
   "data":[
      {
         "id":null
         , "product_id":"product"
         , "product_name":"product"
         , "company_id":"a"
         , "grade":"A"
         , "intent_score":"10"
         , "profile_fit":"Strong"
         , "company_buying_stage":"A"
         , "company_intent_score":"10"
         , "company_profile_fit":"Strong"
         , "company_profile_score":1
         , "txn_id":1
         , "updated":"2017-01-01 02:51:01"
      }
   ]
}